### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by vguenichon** [miguelpeixe/WP_Query_Multisite#2]
But how do you use this class ? Where do I drop the files to use it on my multisite installation ?
Thanks in advance for this help to a non-completeley-dev guy ;-)

**Comment by miguelpeixe** [comment]
You should use it inside your theme. A good approach would be placing the class file inside your `includes` directory on the theme. Could be `inc/` directory. Than you should include in your `functions.php` file like this: 

```php
include_once(TEMPLATEPATH . 'inc/multisite-query.php');
```

**Comment by vguenichon** [comment]
Thanks a lot Miguel. Will try it soon.
